build_defaults: &build_defaults
  docker:
    - image: circleci/node:12-stretch
orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
  build:
    <<: *build_defaults
    steps:
      - checkout
      - run:
          name: Add node_modules/bin to PATH
          command: echo 'export PATH=~/project/node_modules/.bin:$PATH' >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            ~/.cache/yarn
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - slack/status:
          fail_only: true
          failure_message: ':red_circle: A $CIRCLE_JOB has failed! You should probably do something about that...'
      # - run:
      #     name: Security check for npm packages
      #     command: yarn audit --groups dependencies --level high
workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build